version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    assignees:
      - "tomahawk_pilot"
    labels:
      - "npm"
      - "dependencies"
