[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]

for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'none';script-src https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-routing.prod.js https://cdn.ampproject.org https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate https://www.google-analytics.com/analytics.js https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js 'sha256-n4rsutzMft7aPSPeLj+b/TkL5pPa3v+pP99me4UTsX0=' 'sha256-+hJG6y05edYT1pVKXICTswLahWm/P2cx61DSDKsS+/s=' 'self';script-src-elem https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-routing.prod.js https://cdn.ampproject.org https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js https://www.google-analytics.com/analytics.js 'sha256-n4rsutzMft7aPSPeLj+b/TkL5pPa3v+pP99me4UTsX0=' 'sha256-+hJG6y05edYT1pVKXICTswLahWm/P2cx61DSDKsS+/s=' 'self';style-src https://fonts.googleapis.com 'self' 'unsafe-inline';font-src  https://fonts.gstatic.com 'self';img-src https://cdn.hellomunnar.in https://www.google-analytics.com 'self';frame-src  'self';object-src 'none';media-src 'self';connect-src https://www.google-analytics.com 'self';frame-ancestors 'self';manifest-src 'self';form-action 'self';worker-src 'self';base-uri 'self';block-all-mixed-content;report-uri https://o516598.ingest.sentry.io/api/5623221/security/?sentry_key=164754926f104a2689683b9b9de3346f;"
