[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]

for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'none';script-src https://cdn.ampproject.org/rtv/012101300534005/v0/amp-auto-lightbox-0.1.js 'self';script-src-elem https://cdn.ampproject.org/rtv/012101300534005/v0/amp-auto-lightbox-0.1.js 'self';style-src https://fonts.googleapis.com 'self';font-src  https://fonts.gstatic.com 'self';img-src https://cdn.hellomunnar.in 'self';frame-src  'self';object-src 'none';media-src 'self';connect-src 'self';frame-ancestors 'self';manifest-src 'self';form-action 'self';worker-src 'self';base-uri 'self';block-all-mixed-content;report-uri https://o516598.ingest.sentry.io/api/5623221/security/?sentry_key=164754926f104a2689683b9b9de3346f;"